/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vistas;

import Conexion.conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lab10
 */
public class Principal extends javax.swing.JFrame {
    conexion con = new conexion();
    Connection cn;
    Statement st;
    ResultSet rs;
    DefaultTableModel modelo;
    int id;
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        Listar();
    }
    
    
    
    void Listar() {
        String sql = "select * from persona";
        try {
            cn=con.getCon();
            st=cn.createStatement();
            rs=st.executeQuery(sql);
            Object[]persona=new Object [4];
            modelo=(DefaultTableModel)tabladatos.getModel();
            while (rs.next()) {
                persona[0]=rs.getInt("id");
                persona[1]=rs.getString("nombre");
                persona[2]=rs.getString("apellido");
                persona[3]=rs.getString("dni");
                modelo.addRow(persona);
            }   
            tabladatos.setModel(modelo);
            System.out.println("listado exitoso");
        } catch (Exception e) {
            System.out.println("error de listado" + e);
        }
    }

     void Agregar () {
        String nombre=txtnombres_23.getText();
        String apellidos=txtapellidos_23.getText();
        String dni=txtdni_23.getText();
        if(nombre.equals("")||apellidos.equals("")||dni.equals("")){
            JOptionPane.showMessageDialog(null,"no se agrego......!!!");
        }else{
            String sql = "insert into persona(nombre,apellido,dni)values('"+nombre+"','"+apellidos+"','"+dni+"')";
            try {
                cn=con.getCon();
                st=cn.createStatement();
                st.executeUpdate(sql);
                System.out.println("agregado exitoso");
                limpiartabla();
            } catch (Exception e) {
                System.out.println("error" + e);
            }
            }
        }
    
     
     void limpiartabla(){
         for(int i=0;i<=tabladatos.getRowCount();i++) {
             modelo.removeRow(i);
             i=i-1;
         }
     }
    
     
     void modificar () {
         String nombre=txtnombres_23.getText();
         String apellidos=txtapellidos_23.getText();
         String dni=txtdni_23.getText();
         String sql="update persona set nombre='"+nombre+"', apellido='"+apellidos+"', dni='"+dni+"' where id= "+id;
         if(nombre.equals("")||apellidos.equals("")||dni.equals("")) {
             JOptionPane.showMessageDialog(null,"debe ingresar datos");
         }else{
             try {
                 cn=con.getCon();
                 st=cn.createStatement();
                 st.executeUpdate(sql);
                 JOptionPane.showMessageDialog(null,"Usuario actualizado");
                 limpiartabla();
             } catch (Exception e) {
                 System.out.println("error al actualizar" + e);
             }
         }
     }
     
     
     
     void eliminar() {
         int filaseleccionado=tabladatos.getSelectedRow();
         if(filaseleccionado==-1) {
             JOptionPane.showMessageDialog(null,"Debe seleccionar fila");
         }else{
             String sql = "delete from persona where id="+id;
             try {
                 cn=con.getCon();
                 st=cn.createStatement();
                 st.executeUpdate(sql);
                 JOptionPane.showMessageDialog(null,"Usuario eliminado con exito.....!!!!");
                 limpiartabla();
             } catch (Exception e) {
             }
         }
     }
     
     
     void nuevo(){
         txtid_23.setText("");
         txtnombres_23.setText("");
         txtapellidos_23.setText("");
         txtdni_23.setText("");
     }
   
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtid_23 = new javax.swing.JTextField();
        txtnombres_23 = new javax.swing.JTextField();
        txtapellidos_23 = new javax.swing.JTextField();
        txtdni_23 = new javax.swing.JTextField();
        btnagregar_23 = new javax.swing.JButton();
        btnmodificar_23 = new javax.swing.JButton();
        btneliminar_23 = new javax.swing.JButton();
        btnnuevo_23 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabladatos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel1.setText("PersonaCRUD");

        jLabel2.setText("ID");

        jLabel3.setText("NOMBRES");

        jLabel4.setText("APELLIDOS");

        jLabel5.setText("DNI");

        txtid_23.setEditable(false);

        btnagregar_23.setText("AGREGAR");
        btnagregar_23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregar_23ActionPerformed(evt);
            }
        });

        btnmodificar_23.setText("MODIFICAR");
        btnmodificar_23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificar_23ActionPerformed(evt);
            }
        });

        btneliminar_23.setText("ELIMINAR");
        btneliminar_23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminar_23ActionPerformed(evt);
            }
        });

        btnnuevo_23.setText("NUEVO");
        btnnuevo_23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevo_23ActionPerformed(evt);
            }
        });

        tabladatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRES", "APELLIDOS", "DNI"
            }
        ));
        tabladatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabladatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabladatos);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(47, 47, 47)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel4)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel5)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel3)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel2))
                        .add(48, 48, 48)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(txtdni_23, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                    .add(txtapellidos_23))
                                .add(33, 33, 33)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(btneliminar_23, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                    .add(btnnuevo_23, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(txtnombres_23, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                    .add(txtid_23))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, btnmodificar_23)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, btnagregar_23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 91, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .add(49, 49, 49))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 119, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(138, 138, 138)))
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 452, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .add(45, 45, 45)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel2)
                            .add(txtid_23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(btnagregar_23))
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(29, 29, 29)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel3)
                                    .add(txtnombres_23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(41, 41, 41))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(btnmodificar_23)
                                .add(28, 28, 28)))
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel4)
                                    .add(txtapellidos_23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(btneliminar_23))
                                .add(59, 59, 59))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(txtdni_23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(btnnuevo_23)
                                .add(jLabel5)))
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 370, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnagregar_23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregar_23ActionPerformed
        Agregar();
        Listar();
// TODO add your handling code here:
    }//GEN-LAST:event_btnagregar_23ActionPerformed

    private void tabladatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabladatosMouseClicked
       int fila=tabladatos.getSelectedRow();
       if(fila==-1) {
           JOptionPane.showMessageDialog(null,"no se selecionado......!!!");
       }else{
           id=Integer.parseInt((String)tabladatos.getValueAt(fila,0).toString());
           String nombre=(String)tabladatos.getValueAt(fila,1);
           String apellidos=(String)tabladatos.getValueAt(fila,2);
           String dni=(String)tabladatos.getValueAt(fila,3);
           txtid_23.setText(""+id);
           txtnombres_23.setText(nombre);
           txtapellidos_23.setText(apellidos);
           txtdni_23.setText(dni);
       }
       
// TODO add your handling code here:
    }//GEN-LAST:event_tabladatosMouseClicked

    private void btnmodificar_23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificar_23ActionPerformed
        modificar();
        Listar();        // TODO add your handling code here:
    }//GEN-LAST:event_btnmodificar_23ActionPerformed

    private void btneliminar_23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminar_23ActionPerformed
        eliminar();
        Listar();
        nuevo();
        // TODO add your handling code here:
    }//GEN-LAST:event_btneliminar_23ActionPerformed

    private void btnnuevo_23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevo_23ActionPerformed
        nuevo();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnuevo_23ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar_23;
    private javax.swing.JButton btneliminar_23;
    private javax.swing.JButton btnmodificar_23;
    private javax.swing.JButton btnnuevo_23;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabladatos;
    private javax.swing.JTextField txtapellidos_23;
    private javax.swing.JTextField txtdni_23;
    private javax.swing.JTextField txtid_23;
    private javax.swing.JTextField txtnombres_23;
    // End of variables declaration//GEN-END:variables

}
